version: "3"

services:

  realworld-nginx:
    image: nginx:latest
    container_name: realworld-nginx
    depends_on: 
      - realworld-frontend
      - realworld-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5600:80

  realworld-backend:
    build: ./backend
    container_name: realworld-backend
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:z
    restart: unless-stopped
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "200k" # 200kb
        max-file: "2"
    environment:
      - TZ=UTC
      - PORT=3100
      - NODE_ENV=production 
      - AWS_PROFILE=wade

  realworld-frontend:
    build: ./frontend
    container_name: realworld-frontend
    restart: unless-stopped
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "200k" # 200kb
        max-file: "2"
    ulimits:
      core: 1024
    depends_on:
      - realworld-backend
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - NEXT_PUBLIC_DOMAIN=18.163.198.37

networks:
  default:
    external:
      name: nginx
