"use strict";

const { Joi } = require("express-validation");

const email = Joi
	.string()
	.email()
	.description("The email address of the user")
	.required();

const password = Joi
	.string()
	.min(3)
	.required();

const name = Joi
	.string()
	.description("The name of the user")
	.min(3)
	.max(64)
	.required();

const login = {
	body: Joi.object({
		user: Joi
			.object({
				email,
				password
			})
			.required()
	})
};

const register = {
	body: Joi.object({
		user: Joi
			.object({
				name,
				email,
				password
			})
			.required()
	})
};

const update = {
	body: Joi.object({
		user: Joi
			.object({
				name,
				email,
				bio: Joi
					.string()
					.description("A short description about the user"),
				image: Joi
					.string()
					.description("Image URL which is used to display on the website"),
				token: Joi
					.string()
					.description("Unique token string generated by the API call"),
				// Optional update
				password: Joi
					.string()
					.min(3)
			})
	})
};

const user = Joi.object({
	name,
	email,
	token: Joi
		.string()
		.description("Unique token string generated by the API call"),
	bio: Joi
		.string()
		.description("A short description about the user"),
	image: Joi
		.string()
		.description("Image URL which is used to display on the website")
});

module.exports = {
	doc: user,
	login,
	register,
	update
};
